language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
# command to install dependencies
install:
  - pip install -q Django==1.3.1 #$DJANGO_VERSION
  - python setup.py -q install

# command to run tests
script: python setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#booktype"
    on_success: change
    on_failure: change
